version: '3.8'

services:
  indexer:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    restart: always
    environment:
      - NODE_ENV=production
      - SUPABASE_HOST=${SUPABASE_HOST}
      - SUPABASE_PASSWORD=${SUPABASE_PASSWORD}
      - DNA_TOKEN=${DNA_TOKEN}
    network_mode: "host" # Required for IPv6 access to Supabase

volumes:
  postgres_data: 