services:
  indexer:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    restart: always
    environment:
      - NODE_ENV=production
      - SUPABASE_HOST=${SUPABASE_HOST}
      - SUPABASE_PASSWORD=${SUPABASE_PASSWORD}
      - DNA_TOKEN=${DNA_TOKEN}
    network_mode: "host"
    command: >
      /bin/bash -c "
        export ENCODED_PASSWORD=$$(node -e 'console.log(encodeURIComponent(process.env.SUPABASE_PASSWORD));') &&
        export POSTGRES_CONNECTION_STRING=postgresql://postgres:$$ENCODED_PASSWORD@$${SUPABASE_HOST}:5432/postgres &&
        echo 'Using connection string with encoded password' &&
        pnpm apibara build &&
        pnpm apibara start --indexer starknet-lifeform
      "

volumes:
  postgres_data: 