version: '3.8'

services:
  indexer:
    image: node:20-slim
    restart: always
    environment:
      - NODE_ENV=production
      - SUPABASE_HOST=${SUPABASE_HOST}
      - SUPABASE_PASSWORD=${SUPABASE_PASSWORD}
      - DNA_TOKEN=${DNA_TOKEN}
      - POSTGRES_CONNECTION_STRING=postgres://postgres:${SUPABASE_PASSWORD}@${SUPABASE_HOST}:5432/postgres
    network_mode: "host"  # Required for IPv6 access to Supabase
    volumes:
      - ..:/app
    working_dir: /app
    command: >
      sh -c "npm install -g pnpm && 
             cd /app && 
             pnpm install --prod && 
             pnpm start"

volumes:
  postgres_data: 