name: Build

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Node version
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: pnpm/action-setup@v4
        with:
          version: 9.10.0
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.11.0
        with:
          mongodb-version: '7.0'
          mongodb-replica-set: rs0
          mongodb-port: 27017
      - name: Install dependencies
        run: pnpm install --strict-peer-dependencies=false
      - name: Run lint
        run: pnpm lint
      - name: Run build
        run: pnpm build
      - name: Run typecheck
        run: pnpm typecheck
      - name: Run test
        run: pnpm test:ci
      - name: Check change files
        run: pnpm beachball check
